Title
========================================================

Chapter 3.

Regression

```{r, cache=T}
library(DLMBook)
f <- file.path(getwd(),"../inst/extdata/P.dat")
capm_1(f)
```

デンマークとスペインの年間投資額
SUTSE

それぞれは線形成長モデル
$$Y_t = \mu_t + v_t $$
$$\mu_t = \mu_{t-1} + \beta_{t} + w_{\mu , t} $$ 
$$\beta_t = \beta_{t-1} + w_{\beta , t} $$

1期先予測と実現値を同時刻で比較するなら,tにおける1期先予測の値を
t+1での実現と比較すればよい.
dlmFiltered objectのyは観測値であり, fは予測値である.
yのi行目はi番目の観測値を表すが、fのi行目はyのi行目に対する予測値を表す.
i+1行目に対する予測値ではないことに注意.
要するに単純に同じ行同士で比較すればよい.

```{r}
library(DLMBook)
mod <- dlmModPoly(order=2)
mod$FF <- mod$FF %x% diag(2)
mod$GG <- mod$GG %x% diag(2)
W1 <- matrix(0,2,2)
W2 <- diag(c(49,437266))
W2[1,2] <- W2[2,1] <- 155
mod$W <- bdiag(W1, W2)
V <- diag(c(72,14353))
V[1,2] <- V[2,1] <- 1018
mod$V <- V
mod$m0 <- rep(0,4)
mod$C0 <- diag(4) * 1e7

invest <- ts(read.table("../inst//extdata/invest2.dat",skip=0
                        , colClasses="numeric")[,]
             , start=1960)
investFilt <- dlmFilter(y=invest, mod)
conf.interval <- 0.5
dt1 <- DLMFilteredPredictionToDF(
  dlmFiltered=investFilt,exclude.indices=c(1:2), columnIndex=1
  , conf.interval=conf.interval)
dt2 <- DLMFilteredPredictionToDF(
  dlmFiltered=investFilt,exclude.indices=c(1), columnIndex=2
  , conf.interval=conf.interval)
print(conf.interval)
dfs <- list(dt1, dt2)
lapply(X=c(1:2), FUN=function(i){
  temp <- dfs[[i]]
  PlotDLMFilteredPredictionDF(dfs=temp)
  NULL
  })
```

**株式の超過収益率**

一見無関係な回帰モデル

SUR model

それぞれは動的回帰モデル
$$Y_{i,t} = \alpha_{i,t} + \beta_{i,t} * x_{i,t} + v_{i,t} $$
$$\alpha_{i,t} = \alpha_{i, t-1}  + w_{1,i,t} $$ 
$$\beta_{i,t} = \beta_{i, t-1}  + w_{2,i,t} $$ 

```{r}
library(DLMBook)
data.path <- "inst/extdata/P.dat"
dat <- read.table(data.path, header=T) * 100
dat.ts <- ts(dat, start=c(1978,1),frequency=12)
y <- dat.ts[,1:4] - dat.ts[,"RKFREE"]
colnames(y) <- colnames(dat)[1:4]
market <- dat.ts[,"MARKET"] - dat.ts[,"RKFREE"]
### Set up the model
m <- NCOL(y)
CAPM <- dlmModReg(X=market)
CAPM$FF <- CAPM$FF %x% diag(m)
capm_1 <- function(file.path="inst/extdata/P.dat", target="IBM", counter.target="MARKET"){
  capm <- read.table(file.path)
  capm.ts <- ts(capm, start = c(1978,1), frequency=12)
  colnames(capm)
  plot(capm.ts)
  target <- capm.ts[,target] - capm.ts[,"RKFREE"]
  x <- capm.ts[,counter.target] - capm.ts[,"RKFREE"]
  outLM <- lm(target ~ x)
  print(outLM$coef)
  acf(outLM$residuals)
  qqnorm(outLM$residuals)
  
  mod <- dlmModReg(X=x, dV=0.00254, m0=c(0,1.5), C0=diag(c(1e+07,1)))
  outF <- dlmFilter(y=target,mod=mod)
  print(outF$m[1 + length(target), ])
  buildCapm <- function(u){
    dlmModReg(X=x, dV=exp(u[1]), dW=exp(u[2:3]))
  }
  outMLE <- dlmMLE(y=target, parm=rep(0,3), build=buildCapm)
  print(exp(outMLE$par))
  print(outMLE$value)
  mod <- buildCapm(outMLE$par)
  outS <- dlmSmooth(y=target, mod)
  plot(dropFirst(outS$s))
}


investFilt <- dlmFilter(y=invest, mod)
conf.interval <- 0.5
dt1 <- DLMFilteredPredictionToDF(
  dlmFiltered=investFilt,exclude.indices=c(1:2), columnIndex=1
  , conf.interval=conf.interval)
dt2 <- DLMFilteredPredictionToDF(
  dlmFiltered=investFilt,exclude.indices=c(1), columnIndex=2
  , conf.interval=conf.interval)
print(conf.interval)
dfs <- list(dt1, dt2)
lapply(X=c(1:2), FUN=function(i){
  temp <- dfs[[i]]
  PlotDLMFilteredPredictionDF(dfs=temp)
  NULL
  })
```
